version: '3.8'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: consaubeo
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: consaubeo
        ports:
            - "3306:3306"
    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
          - ".:/app"
        ports:
          - "3000:3000"
        depends_on:
          - db
        links:
          - db
        environment:
          DB_USER: root
          DB_NAME: app
          DB_PASSWORD: consaubeo
          DB_HOST: db